name: GroundMC_Lobby_Plugin
version: 1.3
author: GiantTreeLP
main: gtlp.groundmc.lobby.LobbyMain

commands:
   lobby:
      description: Lobby commands
      usage: "Usage: /<command> <additem|help|maketp> [parameters]"
      aliases: [lb]
   friend:
      description: Friendship commands
      usage: "Usage: /<command> <add|remove|status|online> <username> [relation]"
      aliases: [fr]
   vanish:
      description: Vanish yourself
      usage: "Usage: /<command>"
      aliases: [v]
   coins:
      description: Information about your coins
      usage: "Usage: /<command>"
      aliases: [money]