name: GroundMCLobbyPlugin
version: 1.8
author: GiantTreeLP
main: net.groundmc.lobby.LobbyMain
depend: [ItemNBTAPI, PointsAPI, StatsDB, CloudNetAPI]
softdepend: [Multiverse-Core]

commands:
   globby:
      description: Lobby commands
      usage: "/<command> [additem|maketp|help|event|debug|set|config] <parameters>"
      aliases: [glb, gl, ghub]
   friend:
      description: Friendship commands
      usage: "/<command> <add|remove|status|online> <username>"
      aliases: [fr]
   friends:
      description: Lists friends
      usage: "/<command>"
      aliases: [frs]
   vanish:
      description: Vanish yourself
      usage: "/<command>"
      aliases: [v]
      permission: groundmc.lobby.vanish
   coins:
      description: Information about your coins
      usage: "/<command>"
      aliases: [money]

permissions:
  groundmc.lobby:
    description: Grants access to all features
    default: op
    children:
      groundmc.lobby.admin: true
  groundmc.lobby.admin:
    description: Grants administrative access to lobby features
    default: op
    children:
      groundmc.lobby.hide_players: true
      groundmc.lobby.silent: true
      groundmc.lobby.vanish: true
  groundmc.lobby.hide_players:
    description: Allows players to hide other players
    default: false
  groundmc.lobby.silent:
    description: Allows players to silence their chat from other players
    default: false
  groundmc.lobby.vanish:
    description: Allows players to vanish out of sight
    default: false
