name: GroundMC_Lobby_Plugin
version: 1.5
author: GiantTreeLP
main: gtlp.groundmc.lobby.LobbyMain
depend: [BukkitDependencyLoader, ItemNBTAPI]
softdepend: [Multiverse-Core]

commands:
   globby:
      description: Lobby commands
      usage: "/<command> [additem|help|maketp] [parameters]"
      aliases: [glb, gl, ghub]
   friend:
      description: Friendship commands
      usage: "/<command> <add|remove|status|online> <username>"
      aliases: [fr]
   friends:
      description: Lists friends
      usage: "/<command>"
      aliases: [frs]
   vanish:
      description: Vanish yourself
      usage: "/<command>"
      aliases: [v]
   coins:
      description: Information about your coins
      usage: "/<command>"
      aliases: [money]
